/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package linter;

import java.io.File;
import java.io.FileNotFoundException;
import java.util.Scanner;

public class App {

    public static void main(String[] args) {
        System.out.println("hello from linter " + args[0]);
        String returnString = theLintr("src/main/resources/gates.js");
        System.out.println(returnString);
    }
//--------------------------------------------------
    public static String theLintr(String filePath)
    {
        Scanner file;
        try {
            file = new Scanner(new File(filePath));
        }catch (FileNotFoundException error)
        {
            System.out.println("Unable to locate file,");
            return "Did not find file";
        }


        int counter = 0;
        String errorString = "";

        while(file.hasNextLine())
        {
            counter++;
            String temp = file.nextLine();
            if(!temp.isBlank())
            {
                char endChar = temp.charAt(temp.length() -1);
                if (!(endChar == ';' ||  endChar == '{' || endChar == '}' || temp.contains("if") || temp.contains("else")))
                {
                    errorString = errorString + "Line " + counter + ": Missing semicolon.\n";
//                    if(errorString.isBlank())
//                    {
//                        errorString = "Line " + counter + ": Missing semicolon.";
//                    }else{
//                        errorString = errorString + "\nLine " + counter + ": Missing semicolon.";
//                    }
                }
            }
        }

        return errorString;
    }
}
