/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.checkerframework.checker.units.qual.A;

import java.util.ArrayList;

public class Restaurant {
    private String name;
    private int restStars;
    private String price;



    //===========restaurant constructor ===================
    public Restaurant(String name, int restStars, String price)
    {
        this.name = name;
        this.restStars = restStars;
        this.price = price;
        String listName = name + "List";
        ArrayList<Reviews> reviewList = new ArrayList<>();

    }


    //================ Getters ============================

    public String getName(){
        return name;
    }

    public int getRestStars(){
        return restStars;
    }

    public String getPrice(){ return price; }

    //=============== Setters ============================

    public void setName(String name) {
        this.name = name;
    }

    public void setRestStars(int restStars) {
        this.restStars = restStars;
    }

    public void setPrice(String price) {
        this.price = price;
    }

    //=================== Methods =============================

    public String toString(){
        return String.format("Name: %s \n Stars: %d \n Price: %s \n", name, restStars, price);
    }

    public void addReview(ArrayList list, Reviews review)
    {
        list.add(review);
    }




}
