/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;


import java.util.ArrayList;

public class Restaurant extends Shop{

    public ArrayList<Reviews> restReviews = new ArrayList<>();

    private String name;
    private int restStars;
    private String price;

    //===========restaurant constructor ===================
    public Restaurant (String name,  String price, String desc, int restStars)
    {
        super(name,price,desc);
        this.name = name;
        this.restStars = restStars;
        this.price = price;

    }

//================ Getters ============================

    public String getName(){
        return name;
    }

    public int getRestStars(){
        return restStars;
    }

    public String getPrice(){ return price; }

    //=============== Setters ============================

    public void setName(String name) {
        name = name;
    }

    public void setRestStars(int restStars) {
        restStars = restStars;
    }

    public void setPrice(String price) {
        price = price;
    }

    //=================== Methods =============================

    public void addReview(String review, String author, int stars)
    {
        Reviews newReview = new Reviews(review, author, stars); // create new review
        newReview.potato = this;                                // add restaurant to review
        this.restReviews.add(newReview);                        // add review to restaurant
    }

    public String toString(){

        String returnString = String.format("Restaurant: %s %s Stars: %d\n", name, price, restStars);

        for(Reviews review : restReviews){
            returnString += String.format("\nReviewer: %s  Rating: %d\n%s\n", review.getAuthor(), review.getReviewStars(),review.getReview());
        }

        return returnString;
    }
}
