/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testRestaurant() {
        Restaurant sharis = new Restaurant("Shari's", 2, "$$$");

        assertEquals("Shari's", sharis.getName());
        assertEquals(2, sharis.getRestStars());
        assertEquals("$$$", sharis.getPrice());

    }

    @Test public void testReviews(){
        Restaurant sharis = new Restaurant("Sharis", 2, "$$$");
        Restaurant bobs = new Restaurant("Bobs", 4, "$$$$");


        sharis.addReview("This restaurant was absolutely average!!","Donald Smith", 4);
        sharis.addReview("The food sucks, wait staff is awesome","Me", 2);
        bobs.addReview("love this place", "Brother Bob", 5);
        bobs.addReview("love this place, Awesome burgers", "Sally", 4);

        // Not sure how to test this?
    }
}
