/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package inheritance;

import org.junit.Test;

import java.util.ArrayList;

import static org.junit.Assert.*;

public class RestaurantTest {
    @Test public void testRestaurant() {
        Restaurant sharis = new Restaurant("Shari's", "$$$","A family dinning restaurant", 2);

        assertEquals("Shari's", sharis.getName());
        assertEquals(2, sharis.getRestStars());
        assertEquals("$$$", sharis.getPrice());

    }

    @Test public void testReviews(){
        Restaurant sharis = new Restaurant("Sharis", "$$$","A family dinning restaurant", 2);
        Restaurant bobs = new Restaurant("Bobs", "$$$$","A burger joint", 4);


        sharis.addReview("This restaurant was absolutely average!!","Donald Smith", 4);
        sharis.addReview("The food sucks, wait staff is awesome","Me", 2);
        bobs.addReview("love this place", "Brother Bob", 5);
        bobs.addReview("love this place, Awesome burgers", "Sally", 4);

        String expected = "Restaurant: Bobs $$$$ Stars: 4\n" +
                "\n" +
                "Reviewer: Brother Bob  Rating: 5\n" +
                "love this place\n" +
                "\n" +
                "Reviewer: Sally  Rating: 4\n" +
                "love this place, Awesome burgers\n";
        assertEquals(expected, bobs.toString());

    }

    @Test public void testShop(){
        Shop jays = new Shop("Jay's", "$$$", "Local grocery store.");

        assertEquals("Jay's",jays.getName());
        assertEquals("$$$", jays.getPrice());
        assertEquals("Local grocery store.", jays.getDesc());
        String expected = "Jay's  price: $$$,  Local grocery store.";
        assertEquals(expected, jays.toString());
    }

    @Test public void testTheater(){
        ArrayList<String> amcMovies = new ArrayList<>();
        Theater amc = new Theater("AMC","$","Place to watch movies on a big screen", amcMovies);

        assertEquals("AMC", amc.getName());

        amc.addMovie("Die Hard");
        amc.addMovie("Finding Nemo");
        amc.addMovie("Avatar");

        String expected = "**** AMC ****\n" +
                "Movie List:\n" +
                "Die Hard\n" +
                "Finding Nemo\n" +
                "Avatar";
        assertEquals(expected, amc.toString());

        amc.removeMovie("Die Hard");
        expected = "**** AMC ****\n" +
                "Movie List:\n" +
                "Finding Nemo\n" +
                "Avatar";
        assertEquals(expected, amc.toString());

        amc.removeMovie("Avatar");
        amc.removeMovie("Finding Nemo");
        expected = "**** AMC ****\n" +
                "Movie List:";
        assertEquals(expected, amc.toString());

        amc.addMovie("Die Hard");
        amc.addMovie("Finding Nemo");
        amc.addMovie("Avatar");
        amc.addReview("Poor movie selection", "PeeWee", 2);
        amc.addReview("Saw Nemo for the first time!!", "Samuel", 4);

        System.out.println("amcTostring" + amc.toString());
    }
}
